initContainers:
  - name: velero-plugin-for-csi
    image: velero/velero-plugin-for-csi:v0.7.0
    volumeMounts:
      - mountPath: /target
        name: plugins
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.9.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: ${bucket}
      config:
        region: ${region}
  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
       region: ${region}

credentials:
  useSecret: false

podAnnotations:
  co.elastic.logs/enabled: "true"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "Addons-Services"
          operator: In
          values:
          - "true"

resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 20m
    memory: 256Mi
