nodeSelector:
  kubernetes.io/os: linux

settings:
  clusterName: ${eks_cluster_id}
  clusterEndpoint: ${eks_cluster_endpoint}

controller:
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      cpu: 100m
      memory: 400Mi

podAnnotations:
  co.elastic.logs/enabled: "true"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "Addons-Services"
          operator: In
          values:
          - "true"

serviceMonitor:
  # -- Specifies whether a ServiceMonitor should be created.
  enabled: ${enable_service_monitor}
