apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: core-dns-hpa-cpu-memory
 namespace: kube-system
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: {{ .Values.corednsdeploymentname}}
 minReplicas: {{ .Values.minReplicas}}
 maxReplicas: {{ .Values.maxReplicas}}
 metrics:
  - type: Resource
    resource:
      name: cpu
      target: 
        type: Utilization
        averageUtilization: {{ .Values.targetCPUUtilizationPercentage}}
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: {{ .Values.targetMemoryUtilizationPercentage}}
