# Formula for controlling the replicas. Adjust according to your needs
#  replicas = max( ceil( cores * 1/coresPerReplica ) , ceil( nodes * 1/nodesPerReplica ) )
#  replicas = min(replicas, max)
#  replicas = max(replicas, min)
config:
  linear:
    coresPerReplica: 2
    nodesPerReplica: 1
    min: 1
    max: 20
    preventSinglePointFailure: true
    includeUnschedulableNodes: true

# Target to scale. In format: deployment/*, replicationcontroller/* or replicaset/* (not case sensitive).
# The following option should be defined in user defined values.yaml using var.helm_config

options:
 target: deployment/coredns

resources:
  limits:
    cpu: 100m
    memory: 150Mi
  requests:
    cpu: 50m
    memory: 75Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "Addons-Services"
          operator: In
          values:
          - "true"
