## Node affinity for particular node in which labels key is "Infra-Services" and value is "true"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "Addons-Services"
          operator: In
          values:
          - "true"

## Using limits and requests

resources:
  limits:
    cpu: 50m
    memory: 250Mi
  requests:
    cpu: 25m
    memory: 250Mi
