controller:
  containerName: controller
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      cpu: 100m
      memory: 400Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "aman-Services"
          operator: In
          values:
          - "true"

settings:
  clusterName: ${eks_cluster_id}
  clusterEndpoint: ${eks_cluster_endpoint}
  eksControlPlane: false
  featureGates:
    spotToSpotConsolidation: true
    nodeRepair: true

service:
  # -- Additional annotations for the Service.
  annotations: {}

schedulerName: default-scheduler
