clusterName: ${eks_cluster_id}
region: ${aws_region}
image:
  repository: ${repository}

ingressClass: ${load_balancer_controller_name}
ingressClassParams:
  name: ${load_balancer_controller_name}
  create: true
  webhookServiceName: ${load_balancer_controller_name}-webhook-service

enableServiceMutatorWebhook: false

nameOverride: ${load_balancer_controller_name}

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "Addons-Services"
          operator: In
          values:
          - "true"

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 100Mi
